# -*- coding: utf-8 -*-
"""
Batch 2: Hunter (52) and Rogue (54) talents
"""

HUNTER = {
    "swift aspects": "Enquanto o Aspecto do Falcão estiver ativo, ataques à distância normais têm %s%% de chance de aumentar a velocidade de ataque à distância em %s%% por %s s. Enquanto o Aspecto do Lobo estiver ativo, ataques corpo a corpo normais têm %s%% de chance de aumentar a velocidade de ataque corpo a corpo em %s%% por %s s.",
    "endurance training": "Adiciona %s%% do seu Vigor ao Vigor dos seus ajudantes e aumenta a vida deles em %s%%.",
    "improved eyes of the beast": "Aumenta a duração dos seus Olhos da Besta em %s s.\n\nEnquanto canaliza Olhos da Besta, seu ajudante causa %s%% de dano adicional e ganha %s%% a mais de regeneração de Foco.",
    "improved primal aspects": "Aumenta o bônus de Esquiva do seu Aspecto do Macaco em %s%%. Enquanto o Aspecto do Lobo estiver ativo, você é curado em %s%% do seu dano corpo a corpo.",
    "improved revive pet": "O tempo de lançamento de Reviver Ajudante é reduzido em %s s, o custo de mana é reduzido em %s%% e a vida com que seu ajudante retorna aumenta em %s%% adicionais.",
    "pathfinding": "Aumenta o bônus de velocidade do seu Aspecto do Guepardo e Aspecto da Matilha em %s%% e aumenta a velocidade de movimento do seu ajudante em %s%%.",
    "coordinated assault": "Atingir um inimigo com Tiro Arcano, Tiro Firme ou Golpe do Rapinante faz com que o próximo ataque do seu ajudante dentro de %s s também golpeie causando dano Físico igual a 20%% do seu Poder de Ataque. Este efeito só ocorre uma vez a cada 3 s.",
    "unleashed fury": "Aumenta o dano causado pelos seus ajudantes em %s%%.",
    "bestial discipline": "Aumenta a regeneração de Foco dos seus ajudantes em %s a cada pulso e reduz o tempo de recarga da habilidade especial deles em %s%%.",
    "improved mend pet": "Aumenta a quantidade curada no seu ajudante por Curar Ajudante em %s%% e concede %s%% de chance de remover %s efeito de Maldição, Doença, Magia ou Veneno a cada pulso.",
    "scent of blood": "Seus ataques têm %s%% de chance de enfurecer seu ajudante, fazendo com que cause %s%% de dano adicional por %s s.",
    "bestial wrath": "Envia seu ajudante em uma fúria, concedendo Faro de Sangue por %s s. Enquanto enfurecido, ele não sente pena, remorso ou medo, e não pode ser impedido a não ser pela morte.",
    "intimidation": "Comanda seu ajudante a intimidar o alvo no próximo ataque corpo a corpo, atordoando-o por %s s e aumentando a geração de ameaça do ajudante em %s%% por %s s.",
    "bestial precision": "Aumenta a chance de acerto físico dos seus ajudantes em %s%% e a chance de acerto com feitiços em %s%%. Além disso, aumenta a perícia de armas dos seus ajudantes em %s.",
    "spirit bond": "Seu ajudante ganha poder de ataque corpo a corpo igual a %s%% do seu poder de ataque à distância e dano mágico igual a %s%% do seu poder de ataque à distância. Enquanto ativo, você e seu ajudante regeneram %s%% da vida total a cada %s s.",
    "frenzy": "Concede ao seu ajudante %s%% de chance de aumentar a velocidade de ataque em %s%% por %s s após desferir um acerto crítico.",
    "kill command": "Comanda seu ajudante a atacar instantaneamente causando 80%% do seu Poder de Ataque. Só pode ser usado após o Caçador desferir um acerto crítico no alvo.",
    "improved concussive shot": "Concede ao seu Tiro Concussivo %s%% de chance de atordoar o alvo por %s s.",
    "efficiency": "Reduz o custo de mana dos seus Tiros e Ferrões em %s%%.",
    "improved stings": "Aumenta o dano da Picada de Serpente em %s%%, o mana drenado pela Picada de Víbora em %s%% e faz a Picada de Escorpídeo reduzir a velocidade de ataque em %s%% adicionais.",
    "lethal shots": "Aumenta a sua chance de acerto crítico com armas de longo alcance em %s%%.",
    "hawk eye": "Aumenta o alcance das suas armas de longo alcance em %s m.",
    "aimed shot": "Um tiro mirado que aumenta o dano à distância em %s.",
    "swiftshot": "Reduz o tempo de recarga do Tiro Arcano em %s s e o tempo de recarga do Tiro Certo em %s s.",
    "endless quiver": "Seu Tiro Automático, Tiro Arcano, Tiro Firme e Tiro Múltiplo têm %s%% de chance de disparar um ataque à distância normal adicional. Este tiro adicional não consome munição.",
    "mortal shots": "Aumenta o bônus de dano de acerto crítico das suas armas de longo alcance em %s%%.",
    "scatter shot": "Um tiro de curto alcance que causa %s%% do dano da arma e desorienta o alvo por %s s. Qualquer dano removerá o efeito. Desativa seu ataque automático ao ser usado.",
    "experimental ammunition": "Seu Tiro Certo causa %s%% a mais de dano como Fogo, Arcano ou Natureza, conforme o efeito ativo:\n• Munição Explosiva: seu próximo Tiro Múltiplo explode causando %s%% de dano a até %s m dos alvos.\n• Munição Venenosa: sua próxima Picada de Serpente causa %s%% a mais de dano e reduz a armadura em %s por %s s.\n• Munição Encantada: seu próximo Tiro Arcano causa %s%% a mais de dano e aumenta o dano mágico sofrido em %s%% por %s s.",
    "piercing shots": "Seus acertos críticos de Tiro Múltiplo, Tiro Firme e Tiro Certo fazem o alvo sangrar, causando %s%% do dano ao longo de %s s. Este dano não gera ameaça.",
    "barrage": "Aumenta o dano do Tiro Múltiplo e Saraivada em %s%% e reduz o tempo de canalização da Saraivada em %s s.",
    "improved marksmanship": "Aumenta o dano do Tiro Firme e Tiro Certo em %s%%.",
    "ranged weapon specialization": "Aumenta o dano que você causa com armas de longo alcance em %s%%.",
    "lock and load": "Seus acertos críticos de Tiro Firme, Tiro Certo e Tiro Arcano têm %s%% de chance de reiniciar a recarga de Tiro Certo e ativar Travar e Carregar, reduzindo o tempo de lançamento em %s s e atingindo todos os inimigos no trajeto. Dura %s s.",
    "improved slaying": "Aumenta todo o dano contra Feras, Gigantes, Draconianos e Humanoides em %s%% e o dano crítico contra eles em %s%% adicionais.",
    "resourcefulness": "Reduz o custo de mana de todas as armadilhas e habilidades corpo a corpo em %s%%.",
    "swift reflexes": "Aumenta a sua chance de Aparar e a velocidade de ataque em %s%%.",
    "entrapment": "Concede à sua Armadilha de Imolação, de Gelo e Explosiva %s%% de chance de prender o alvo, impedindo movimento por %s s.",
    "savage strikes": "Aumenta o dano da arma secundária em %s%% e a chance de acerto crítico de Dilacerar, Golpe do Rapinante, Mordida de Mangusto, Trinchar e Cortar Tendão em %s%%.",
    "improved wing clip": "Concede à sua habilidade Cortar Tendão %s%% de chance de imobilizar o alvo por %s s.",
    "alone against the world": "Enquanto você não tiver ajudante sob seu controle, todo o dano causado é aumentado em %s%%.",
    "planning ahead": "A duração de Armadilha Congelante e de Gelo e o dano de Imolação e Explosiva aumentam em %s%% se não forem acionadas nos primeiros %s s após armadas.",
    "survivalist": "Aumenta a sua vida total em %s%%.",
    "carve": "Um ataque em arco que atinge até %s inimigos em um cone de %s m à sua frente, causando %s%% do dano da arma.\nCompartilha tempo de recarga com Tiro Múltiplo.",
    "deterrence": "Quando ativado, aumenta a sua chance de Esquiva e Aparo em %s%% por %s s.",
    "stinging nettle": "Sua Mordida de Mangusto e armadilhas de Fogo acionadas aplicam seu grau mais alto de Picada de Serpente por %s%% da duração, ignorando resistências e imunidades.",
    "surefooted": "Aumenta a chance de acerto em %s%%, e em mais %s%% ao empunhar duas armas.\nAlém disso, aumenta a chance de resistir a efeitos redutores de movimento em %s%%.",
    "improved feign death": "Reduz a chance da sua habilidade Fingir de Morto ser resistida em %s%%.",
    "killer instinct": "Aumenta a sua chance de acerto crítico com todos os ataques em %s%% e o bônus de dano de acerto crítico corpo a corpo em %s%%.",
    "trap mastery": "Aumenta a duração de Armadilha Congelante e de Gelo em %s%% e o dano de Imolação e Explosiva em %s%%. Além disso, reduz a chance de inimigos resistirem às armadilhas em %s%%.",
    "lacerate": "Aprofunda a ferida aberta do alvo, causando dano igual a %s%% do seu Poder de Ataque corpo a corpo e fazendo-o sangrar em %s%% desse dano ao longo de %s s. Requer acerto crítico prévio. Causa 15%% a mais de dano pelas costas/lados.",
    "vicious strikes": "Reduz o tempo de recarga de Golpe do Rapinante e Mordida de Mangusto em %s s e aumenta o dano causado em %s%%.",
    "untamed trapper": "Reduz o custo de mana de Armadilha de Imolação e Explosiva em %s%% e aumenta o dano delas com base no seu Poder de Ataque corpo a corpo. Além disso, permite armar todas as armadilhas em combate."
}

ROGUE = {
    "improved eviscerate": "Aumenta o dano causado pela sua habilidade Eviscerar em %s%%.",
    "remorseless attacks": "Após matar um oponente que conceda experiência ou honra, concede %s%% a mais de chance de acerto crítico na sua próxima habilidade geradora de pontos de combo. Dura %s s.",
    "malice": "Aumenta a sua chance de acerto crítico em %s%%.",
    "ruthlessness": "Concede aos seus golpes finais %s%% de chance de adicionar um ponto de combo ao alvo.",
    "murder": "Aumenta todo o dano causado contra Humanoides, Gigantes, Feras e Draconianos em %s%%.",
    "improved blade tactics": "Aumenta a duração das suas habilidades Fatiar e Picar e Florescer em %s%%.",
    "relentless strikes": "Seus golpes finais têm %s%% de chance por ponto de combo de restaurar %s de energia e aumentar o dano dos seus golpes finais em %s%% por %s s. Acumula até %s vezes.",
    "throwing weapon specialization": "Aumenta o alcance de Arremessar e Arremesso Mortal em %s m e concede ao Arremesso Mortal %s%% de chance de aplicar o veneno da sua arma secundária.",
    "lethality": "Aumenta o bônus de dano de acerto crítico das suas habilidades que geram pontos de combo em %s%%.",
    "taste for blood": "Aumenta a duração da sua Ruptura em %s s. Cada vez que você usa Ruptura, seu dano corpo a corpo aumenta em %s%% por ponto de combo por toda a duração, independentemente de aplicação bem-sucedida.",
    "vile poisons": "Aumenta o dano causado pelos seus venenos em %s%% e concede aos seus venenos %s%% adicionais de chance de resistir a efeitos de dissipação.",
    "improved poisons": "Aumenta a chance de aplicar venenos ao seu alvo em %s%%.",
    "efficient poisons": "Reduz a chance dos seus venenos serem resistidos em %s%% e concede às aplicações de veneno %s%% de chance de não consumir uma carga.",
    "envenom": "Golpe final que aumenta a eficácia e a chance de aplicar venenos ao alvo em %s%%. Dura mais tempo por ponto de combo:\n• 1 ponto: 12 s\n• 2 pontos: 16 s\n• 3 pontos: 20 s\n• 4 pontos: 24 s\n• 5 pontos: 28 s.",
    "cold blood": "Quando ativado, aumenta a chance de acerto crítico do seu próximo Golpe Sinistro, Apunhalar, Emboscada, Ataque Nocivo ou Eviscerar em %s%%.",
    "vigor": "Aumenta a sua Energia máxima em %s. Cada vez que você aplica veneno ao alvo, você tem %s%% de chance de ganhar %s de Energia.",
    "seal fate": "Seus acertos críticos de habilidades que concedem pontos de combo têm %s%% de chance de adicionar um ponto de combo adicional.",
    "noxious assault": "Golpeia com ambas as armas, causando %s de dano mais 30%% do seu Poder de Ataque e aplica venenos de ambas as armas. Concede %s ponto(s) de combo.",
    "opportunity": "Aumenta o dano causado ao golpear por trás com suas habilidades Apunhalar, Garrote ou Emboscada em %s%%.",
    "lightning reflexes": "Aumenta a sua chance de Esquiva em %s%%.",
    "improved backstab": "Aumenta a chance de acerto crítico da sua habilidade Apunhalar em %s%% e concede %s%% de chance de conceder um ponto de combo adicional.",
    "precision": "Aumenta a sua chance de acerto com armas de combate corpo a corpo em %s%%.",
    "riposte": "Um ataque que se torna ativo após aparar o ataque de um oponente. Este ataque causa %s%% do dano da arma e desarma o alvo por %s s.",
    "improved sprint": "Concede %s%% de chance de remover todos os efeitos de redução de movimento ao ativar sua habilidade Disparada.",
    "setup": "Concede a você %s%% de chance de adicionar um ponto de combo ao alvo após esquivar do ataque dele ou resistir totalmente a um de seus feitiços.",
    "improved kick": "Concede à sua habilidade Chute %s%% de chance de silenciar o alvo por %s s.",
    "concussive blows": "Concede a você %s%% de chance de atordoar o alvo por %s s com uma maça.",
    "close quarters combat": "Aumenta a sua chance de acerto crítico com Maças, Adagas e Armas de Punho em %s%%.",
    "surprise attack": "Um golpe surpresa que causa 25%% do seu Poder de Ataque como dano. Só pode ser usado após o alvo esquivar e não pode ser bloqueado, esquivado ou aparado. Concede %s ponto(s) de combo.",
    "hack and slash": "Concede a você %s%% de chance de desferir um ataque extra no mesmo alvo após causar dano com seu Machado ou Espada.",
    "weapon expertise": "Aumenta a sua perícia com Machados, Adagas, Armas de Punho, Maças e Espadas em %s.",
    "blade rush": "Aumenta a sua velocidade de ataque corpo a corpo em %s%% e reduz o intervalo entre pulsos de regeneração de Energia com base na sua Agilidade.",
    "aggression": "Aumenta o dano das suas habilidades Golpe Sinistro, Eviscerar, Resposta e Ataque Surpresa em %s%%.",
    "adrenaline rush": "Aumenta a sua taxa de regeneração de Energia em %s%% por %s s.",
    "camouflage": "Aumenta a sua velocidade enquanto estiver em modo Furtivo em %s%% e reduz o tempo de recarga da Furtividade em %s s. Além disso, reduz a chance de inimigos detectarem você.",
    "improved expose armor": "Aumenta a armadura reduzida pela sua habilidade Expor Armadura em %s%%.",
    "improved gouge": "Aumenta a duração do efeito da sua habilidade Golpeie em %s s.",
    "improved ambush": "Aumenta a chance de acerto crítico da sua habilidade Emboscada em %s%%. Sua Emboscada restitui %s de Energia se não resultar em acerto crítico.",
    "elusiveness": "Reduz o tempo de recarga das suas habilidades Sumir e Cegar em %s s.",
    "serrated blades": "Aumenta o dano causado pelas suas habilidades Ruptura e Garrote em %s%% e faz com que seus ataques ignorem %s da Armadura do alvo.",
    "initiative": "Concede a você %s%% de chance de adicionar um ponto de combo adicional ao alvo ao usar suas habilidades Emboscada, Garrote ou Golpe Baixo.",
    "improved ghostly strike": "Seu Golpe Fantasmagórico aumenta a sua velocidade de movimento em %s%% e a dos membros do seu grupo a até %s m em %s%% por %s s. Além disso, reduz o custo de Energia em %s.",
    "smoke bomb": "Cria uma nuvem de fumaça densa em um raio de %s m ao seu redor por %s s. Todos os alvos dentro da fumaça têm %s%% a menos de chance de serem atingidos por ataques e feitiços pela duração.",
    "hemorrhage": "Um ataque instantâneo que causa %s%% do dano da arma e faz o alvo sangrar, aumentando o dano Físico sofrido em %s%%. Dura %s cargas ou %s s. Concede %s ponto(s) de combo.",
    "cloaked in shadows": "Sempre que usar Sumir, você e membros do grupo a até %s m são envoltos em sombras, ganhando uma barreira que absorve até %s%% da sua vida máxima por %s s.",
    "blackjack": "Suas habilidades Aturdir e Cegar reduzem o dano causado pelo alvo em %s%% por %s s quando o efeito termina ou falha. Além disso, concede %s%% de chance de retornar à furtividade após usar Aturdir.",
    "blinding haze": "Reduz o custo de Energia da sua Distração em %s. Além disso, alvos atingidos pela Distração têm a chance de acerto reduzida em %s%% por %s s. Este efeito tem aplicação garantida.",
    "dirty deeds": "Reduz o custo de Energia das suas habilidades Golpe Baixo e Garrote em %s.",
    "preparation": "Quando ativado, encerra imediatamente o tempo de recarga de todas as suas outras habilidades de Ladino.",
    "shadow of death": "Golpe final que grava um sigilo no alvo por %s s. O sigilo acumula dano com base no dano sofrido pelo alvo, até um limite do seu Poder de Ataque, liberando o dano ao expirar:\n• 1 ponto: 10%% acumulado, até 50%% de PA\n• 2 pontos: 20%% acumulado, até 100%% de PA\n• 3 pontos: 30%% acumulado, até 150%% de PA\n• 4 pontos: 40%% acumulado, até 200%% de PA\n• 5 pontos: 50%% acumulado, até 250%% de PA.",
    "bloody mess": "Reduz o custo de Energia da sua Hemorragia em %s e aumenta o bônus de dano Físico causado da Hemorragia em %s%%.",
    "honor among thieves": "Acertos críticos físicos desferidos por você ou membros do grupo a até %s m concedem a você %s de Energia.",
    "tricks of the trade": "Seus golpes de abertura têm %s%% de chance e seus golpes finais têm %s%% de chance por ponto de combo de aumentar a chance de acerto crítico dos membros do grupo em %s%% por %s s. Acumula até %s vezes.",
    "mark for death": "Um golpe marcador que causa %s%% do dano da arma e revela as fraquezas do alvo, aumentando o Poder de Ataque dos membros do grupo em 30%% e o dano mágico em até 18%% do seu PA por %s s. Não pode ser bloqueado, esquivado ou aparado. Concede %s ponto(s) de combo."
}
