# -*- coding: utf-8 -*-
"""
Batch 4: Warlock (52) and Druid (53) talents
"""

WARLOCK = {
    "suppression": "Reduz a chance de oponentes resistirem aos seus feitiços de Aflição em %s%%.",
    "improved corruption": "Reduz o tempo de lançamento do seu feitiço Corrupção em %s s.",
    "improved curse of weakness": "Aumenta a redução de velocidade de ataque da sua Maldição da Fraqueza em %s%%.",
    "resilient shadows": "Reduz a chance dos seus feitiços de Aflição serem dissipados em %s%% adicionais.",
    "improved life tap": "Aumenta a quantidade de mana concedida pelo seu feitiço Conversão de Vida em %s%%.",
    "improved drains": "Aumenta a eficácia de Drenar Alma, Drenar Vida e Drenar Mana em %s%%.",
    "improved curse of agony": "Aumenta o dano causado pela sua Maldição da Agonia em %s%%.",
    "fel concentration": "Concede aos seus feitiços de Aflição %s%% de chance de não perderem tempo de lançamento ao sofrer dano.",
    "curse of exhaustion": "Reduz a velocidade de movimento do alvo em %s%% por %s s. Apenas uma Maldição por Bruxo pode estar ativa em um alvo.",
    "grim reach": "Aumenta o alcance dos seus feitiços de Aflição em %s%%.",
    "nightfall": "Seus feitiços Corrupção, Colheita Sombria e Drenar têm %s%% de chance de fazer você entrar em Transe Sombrio ao causar dano, reduzindo o tempo de lançamento da próxima Seta Sombria em %s%% e garantindo o acerto.",
    "soul siphon": "Aumenta o dano de Drenar Alma, Colheita Sombria e Espiral da Morte em %s%% adicionais para cada efeito de Aflição no alvo, até no máximo 4 efeitos.",
    "rapid deterioration": "Aumenta a velocidade de lançamento dos seus feitiços de Aflição em %s%%. Efeitos que aumentam velocidade aceleram a frequência dos pulsos dos seus feitiços contínuos com 50%% de eficácia.",
    "siphon life": "Transfere %s de vida do alvo para o lançador ao longo de %s s.",
    "improved curse of exhaustion": "Aumenta a redução de velocidade da sua Maldição da Exaustão em %s%%.",
    "malediction": "Sua Maldição da Agonia pode ser usada junto com outras maldições, exceto Maldição da Perdição. Aplicar Imprudência, Sombras ou Elementos também aplica o grau mais alto de Agonia.",
    "shadow mastery": "Aumenta o dano causado ou vida drenada pelos seus feitiços de Sombra em %s%%.",
    "dark harvest": "Colhe a vida do alvo, causando %s de dano de Sombra ao longo de %s s. Durante a canalização, o intervalo entre pulsos de Aflição é reduzido em %s%%. Se o alvo morrer durante o canal, a recarga é reiniciada.",
    "sinister pursuit": "Aumenta a velocidade de movimento dos seus demônios em %s%%.",
    "demonic embrace": "Aumenta o seu Vigor total em %s%%, mas reduz o seu Espírito total em %s%%.",
    "soul entrapment": "Enquanto não tiver demônio sob seu controle, todo o dano causado é aumentado em %s%%.",
    "soul funnel": "Aumenta a vida transferida pelo Canalizar Vida em %s%% da vida restante do demônio e o mana transferido pelo Canalizar Mana em %s%% do mana restante do demônio. Drena %s%% desse valor de você.",
    "demonic aegis": "Aumenta a eficácia do seu feitiço Armadura Demoníaca em %s%%.",
    "fel intellect": "Aumenta o Intelecto do seu demônio em %s%% do seu Intelecto total e permite que %s%% da regeneração de mana continue durante o lançamento.",
    "fel domination": "Seu próximo feitiço de invocação de demônio comum tem o tempo de lançamento reduzido em %s s e o custo de mana reduzido em %s%%.",
    "fel stamina": "Aumenta o Vigor do seu demônio em %s%% do seu Vigor total e reduz a chance de ele sofrer acertos críticos em %s%%.",
    "demonic sacrifice": "Quando ativado, sacrifica seu demônio invocado para conceder um efeito único:\n• Diabrete: aumenta o dano mágico em %s%%.\n• Emissário: regenera %s%% da vida a cada %s s.\n• Sucubo: reduz a ameaça em %s%%.\n• Caçador: regenera %s%% do mana a cada %s s.",
    "improved stones": "Aumenta a eficácia de Pedra Vil, Pedra da Cólera, Pedra do Caos e Pedra Mágica em %s%%, e aumenta o bônus de acerto crítico da Pedra de Fogo em %s%%.",
    "master summoner": "Reduz o tempo de lançamento de Diabrete, Emissário, Súcubo e Caçador em %s s e o custo de mana em %s%%. Reduz a recarga de Inferno, Ritual da Perdição e Portal Demoníaco em %s%%.",
    "nether studies": "Aumenta o efeito de Sedução da Súcubo, Tormento do Emissário, Pacto de Sangue do Diabrete e Sangue Maculado do Caçador em %s%%.",
    "unholy power": "Aumenta o dano causado pelos seus demônios em %s%%.",
    "power overwhelming": "Canaliza energia no seu demônio, quebrando todos os efeitos de controle e aumentando o dano causado em %s%% por %s s. O demônio sofre %s%% da vida máxima como dano pela duração.",
    "demonic precision": "Seus demônios ganham %s%% a mais de chance de acerto e crítico, e herdam %s%% da sua chance de acerto e crítico com feitiços como acerto e crítico corpo a corpo e mágico.",
    "master demonologist": "Concede ao Bruxo e ao demônio um efeito enquanto o demônio estiver ativo:\n• Diabrete: reduz custos de feitiços em %s%%.\n• Emissário: reduz dano físico sofrido em %s%%.\n• Súcubo: aumenta todo dano causado em %s%%.\n• Caçador: aumenta todas as resistências em %s.\n• Demônios Maiores: aumenta crítico mágico em %s%%.",
    "unleashed potential": "Acertos de feitiços de dano direto permitem ao seu demônio se beneficiar de %s%% do seu bônus de dano de Fogo e Sombra por %s s. Pulsos de canalização renovam a duração. Acumula até %s vezes.",
    "soul link": "Enquanto um demônio estiver sob seu controle, o dano causado por você e seu demônio aumenta em %s%%. Além disso, %s%% de todo o dano sofrido é transferido para o demônio. Demônios não quebram mais o controle prematuramente.",
    "shadow vulnerability": "Sua Seta Sombria e Drenar Alma têm %s%% de chance de aumentar o dano de Sombra causado ao alvo em %s%% por %s s, com maior chance de acerto em golpes críticos.",
    "cataclysm": "Reduz o custo de mana dos seus feitiços de Destruição em %s%%.",
    "demonic swiftness": "Reduz o tempo de lançamento da Seta de Fogo do Diabrete em %s s e a recarga do Açoite da Dor da Súcubo em %s s.",
    "bane": "Reduz o tempo de lançamento dos seus feitiços Seta Sombria, Dor Agoniante e Imolação em %s s e do seu Fogo Flamejante em %s s.",
    "aftermath": "Aumenta o dano periódico do seu feitiço Imolação em %s%% e concede aos seus feitiços de Destruição %s%% de chance de reduzir a velocidade do alvo em 50%% por %s s.",
    "intensity": "Concede aos seus feitiços de Fogo %s%% de chance de não perderem tempo de lançamento ao sofrer dano.",
    "shadowburn": "Atinge instantaneamente o alvo com %s de dano de Sombra. Se o alvo morrer dentro de %s s e conceder honra ou experiência, o lançador ganha um Fragmento de Alma.",
    "devastation": "Aumenta a chance de acerto crítico dos seus feitiços de Destruição em %s%%.",
    "pyroclasm": "Concede aos seus feitiços Chuva de Fogo, Fogo do Inferno, Conflagrar e Fogo da Alma 13%% de chance de atordoar o alvo por %s s.",
    "destructive reach": "Aumenta o alcance dos seus feitiços de Destruição em %s%% e o raio do seu Fogo do Inferno em %s%%.",
    "improved searing pain": "Aumenta a chance de acerto crítico do seu feitiço Dor Agoniante em %s%%.",
    "improved soul fire": "Seu Fogo da Alma tem %s%% de chance de restituir um Fragmento de Alma e aumentar o dano de Fogo em %s%% por %s s.",
    "improved immolate": "Aumenta o dano do seu feitiço Imolação em %s%%.",
    "ruin": "Aumenta o bônus de dano de acerto crítico dos seus feitiços de Destruição em %s%%.",
    "emberstorm": "Aumenta o dano causado pelos seus feitiços de Fogo em %s%%.",
    "conflagrate": "Incendeia o alvo, causando %s de dano de Fogo e consumindo 3 s da sua Imolação para causar uma quantidade equivalente de dano."
}

DRUID = {
    "improved wrath": "Reduz o tempo de lançamento e a recarga global do seu feitiço Cólera em %s s.",
    "nature's grasp": "Enquanto ativo, qualquer inimigo que golpear você tem %s%% de chance de ser afetado por Raízes Sufocantes. Usável apenas ao ar livre. Cargas: %s. Dura %s s.",
    "improved nature's grasp": "Aumenta a chance de o seu Abraço da Natureza enredar um inimigo em %s%%.",
    "sylvan blessing": "Concede %s%% de chance, após matar um alvo que conceda honra ou experiência, de permitir que seu mana regenere a %s%% enquanto lança feitiços por %s s.",
    "guidance of the dream": "Concede %s%% de chance de evitar interrupções causadas por dano enquanto lança feitiços de Equilíbrio.",
    "improved moonfire": "Aumenta o dano e a chance de acerto crítico do seu feitiço Fogo Lunar em %s%%.",
    "natural weapons": "Aumenta o dano físico causado em todas as formas em %s%% e aumenta a chance de acerto com ataques e feitiços em %s%%.",
    "natural shapeshifter": "Reduz o custo de mana de todas as metamorfoses em %s%%.",
    "moonfury": "Aumenta o dano dos seus feitiços Fogo Estelar, Fogo Lunar, Furacão, Enxame de Insetos e Cólera em %s%%.",
    "omen of clarity": "Imbui o Druida com energia natural. Ataques corpo a corpo e lançamentos de feitiços de dano têm chance de entrar em Lançamento Livre, reduzindo o custo de Mana, Raiva ou Energia da próxima habilidade em %s%%.",
    "nature's reach": "Aumenta o alcance de Cólera, Raízes Sufocantes, Fogo das Fadas, Fogo Lunar, Fogo Estelar, Enxame de Insetos, Furacão e feitiços de cura em %s%%.",
    "vengeance": "Aumenta o bônus de dano de acerto crítico dos seus feitiços Fogo Estelar, Fogo Lunar e Cólera em %s%%.",
    "moonglow": "Reduz o custo de mana dos seus feitiços Fogo Lunar, Fogo Estelar, Cólera, Furacão, Enxame de Insetos, Toque de Cura, Recrescimento e Rejuvenescimento em %s%%.",
    "owlkin frenzy": "Sofrer dano na Forma de Luniscado tem %s%% de chance de enfurecer você, concedendo %s%% de chance de evitar interrupções ao lançar e regenerando %s%% do seu mana máximo por segundo por %s s. Ocorre a cada 30 s.",
    "moonkin form": "Transforma o Druida em Luniscado. A armadura de itens aumenta em %s%%, o custo de feitiços de Equilíbrio diminui em 20%% e o acerto crítico com feitiços de membros do grupo a até 30 m aumenta em 3%%. Transforma liberta de Polimorfia e lentidões.",
    "improved starfire": "Reduz o tempo de lançamento de Fogo Estelar em %s s e concede %s%% de chance de atordoar o alvo por %s s.",
    "balance of all things": "Causar dano a um alvo afetado por Enxame de Insetos com Cólera restitui %s%% do seu custo de mana. Fogo Estelar tem %s%% a mais de chance de acerto crítico contra alvos com Fogo Lunar.",
    "gale winds": "Reduz o custo de mana de Furacão em %s%% e faz com que reduza a velocidade de ataque dos inimigos afetados em %s%%.",
    "eclipse": "Alinha energias naturais e astrais. Cólera tem %s%% de chance de conceder Eclipse Arcano. Fogo Estelar tem %s%% de chance de conceder Eclipse da Natureza. Bônus de dano: %s%% mais %s%% do seu crítico mágico por %s s.",
    "ferocity": "Reduz o custo das suas habilidades Espancar, Varredura, Mordida Feroz, Garra e Rasgar em %s de Raiva ou Energia.",
    "feral aggression": "Aumenta a redução de Poder de Ataque do Rugido Desmoralizante em %s%% e o dano causado pela sua Mordida Feroz em %s%%.",
    "feral instinct": "Aumenta a ameaça gerada nas Formas de Urso e Urso Hediondo em %s%% e reduz a chance de inimigos detectarem você enquanto estiver em Sorrateiro.",
    "brutal impact": "Aumenta a duração do atordoamento das suas habilidades Esmagar e Bote em %s s.",
    "thick hide": "Aumenta o valor de armadura dos seus itens em %s%%.",
    "open wounds": "Aumenta o dano de Rasgar em %s%%. Além disso, aumenta o dano de Garra em %s%% para cada efeito de sangramento ativo no alvo.",
    "feral swiftness": "Aumenta a sua velocidade de movimento em %s%% ao ar livre na Forma de Felino e aumenta a sua chance de Esquiva nas Formas de Urso e Felino em %s%%.",
    "feral charge": "Investe contra o inimigo, imobilizando-o e interrompendo qualquer feitiço em lançamento por %s s.",
    "sharpened claws": "Aumenta a sua chance de acerto crítico nas Formas de Urso, Urso Hediondo e Felino em %s%%.",
    "primal fury": "Concede %s%% de chance de gerar %s de Raiva adicional ao desferir um acerto crítico na Forma de Urso, e acertos críticos na Forma de Felino têm chance de conceder um ponto de combo adicional.",
    "predatory strikes": "Aumenta o seu poder de ataque corpo a corpo nas Formas de Felino e Urso em %s%%. Além disso, aumenta o dano de Garra, Rasgar, Espancar, Varredura e Mordida Feroz em %s%%.",
    "blood frenzy": "Aumenta a duração da Fúria do Tigre em %s s e faz Enfurecer gerar instantaneamente %s de Raiva. Fúria do Tigre e Enfurecer aumentam a velocidade de ataque em %s%% por %s s.",
    "improved shred": "Aumenta o dano de Estraçalhar em %s%% e reduz o seu custo de Energia em %s.",
    "ancient brutality": "Esquivar de um ataque na Forma de Urso gera %s de Raiva por segundo por %s s (uma vez a cada 9 s). Na Forma de Felino, pulsos de sangramento restauram %s de Energia.",
    "berserk": "Remove todos os efeitos de Medo e aumenta a regeneração de energia em 100%% na Forma de Felino, e aumenta a vida total em 20%% na Forma de Urso. Dura 20 s.",
    "heart of the wild": "Aumenta o Intelecto em %s%%. Na Forma de Urso o Vigor aumenta em %s%% e na Forma de Felino a Força aumenta em %s%%.",
    "carnage": "Espancar, Varredura e Mordida Feroz devolvem %s%% do seu dano como cura para você. Mordida Feroz tem %s%% de chance por ponto de combo de renovar Rasgar e conceder um ponto de combo adicional.",
    "leader of the pack": "Nas Formas de Felino e Urso, Líder da Matilha aumenta a chance de acerto crítico corpo a corpo e à distância de membros do grupo a até %s m em %s%%.",
    "improved mark of the wild": "Aumenta os efeitos dos feitiços Marca do Ermo e Dádiva do Ermo em %s%%.",
    "furor": "Concede %s%% de chance de obter %s de Raiva ao se transformar em Urso ou %s de Energia ao se transformar em Felino.",
    "improved healing touch": "Reduz o tempo de lançamento do seu feitiço Toque de Cura em %s s.",
    "nature's focus": "Concede %s%% de chance de evitar interrupções causadas por dano enquanto lança Toque de Cura, Recrescimento e Tranqüilidade.",
    "subtlety": "Reduz a ameaça gerada pelos seus feitiços em %s%%.",
    "swiftmend": "Consome um efeito de Rejuvenescimento ou Recrescimento em um aliado para curá-lo instantaneamente em um valor equivalente a 12 s de Rejuvenescimento ou 18 s de Recrescimento.",
    "genesis": "Aumenta o dano e a cura dos seus feitiços e efeitos mágicos periódicos em %s%%.",
    "reflection": "Permite que %s%% da sua regeneração de mana continue durante o lançamento.",
    "gift of nature": "Aumenta a eficácia de todos os feitiços de cura em %s%%.",
    "tranquil spirit": "Reduz o custo de mana dos seus feitiços Toque de Cura, Recrescimento e Tranqüilidade em %s%%.",
    "aessina's bloom": "Curar um alvo afetado por Recrescimento ou Rejuvenescimento com Toque de Cura reduz o tempo de lançamento do próximo Toque de Cura em %s s e restitui %s%% do custo de mana por %s s.",
    "nature's swiftness": "Quando ativado, seu próximo feitiço de Natureza torna-se um feitiço instantâneo.",
    "preservation": "Aumenta a cura periódica de Recrescimento em %s%% se o aliado estiver afetado por Rejuvenescimento.",
    "improved regrowth": "Aumenta a chance de efeito crítico do seu feitiço Recrescimento em %s%%.",
    "improved tranquility": "Aumenta a cura realizada pelo seu feitiço Tranqüilidade em %s%%.",
    "tree of life form": "Transforma-se na Árvore da Vida. Armadura de itens aumenta em %s%%, poder de cura de aliados próximos aumenta em %s%% do seu espírito, velocidade reduz em %s%% e custos de curas periódicas reduzem em 20%%. Liberta de Polimorfia e lentidões."
}
