# -*- coding: utf-8 -*-
"""
Batch 3: Priest (51) and Mage (55) talents
"""

PRIEST = {
    "piercing light": "Reduz a chance dos inimigos resistirem aos seus feitiços Sagrados e de Disciplina em %s%%.",
    "mental agility": "Reduz o custo de mana dos seus feitiços instantâneos e feitiços ofensivos Sagrados e de Disciplina em %s%%.",
    "silent resolve": "Reduz a ameaça gerada pelos seus feitiços em %s%%.",
    "unbreakable will": "Aumenta a sua chance de resistir a efeitos de Atordoamento, Medo e Silêncio em %s%% adicionais.",
    "blessed concentration": "Concede %s%% de chance de obter Lançamento Focado por %s s após sofrer um acerto crítico corpo a corpo ou à distância. Impede perda de tempo de lançamento ao sofrer dano e aumenta a resistência a Interrupções em %s%%.",
    "improved power word: fortitude": "Aumenta o efeito dos seus feitiços Palavra de Poder: Fortitude e Oração de Fortitude em %s%%.",
    "improved inner fire": "Aumenta os efeitos do seu feitiço Fogo Interior em %s%%.",
    "inner focus": "Quando ativado, reduz o custo de mana do seu próximo feitiço em %s%% e aumenta a sua chance de efeito crítico em %s%%.",
    "improved power word: shield": "Aumenta a quantidade de dano absorvida pela sua Palavra de Poder: Escudo em %s%%.",
    "meditation": "Permite que %s%% da sua regeneração de mana continue durante o lançamento de feitiços.",
    "searing light": "Acertos críticos dos seus feitiços de dano Sagrados e de Disciplina têm %s%% de chance de tornar o seu próximo Punição instantâneo e custar %s%% a menos de mana. Dura %s s.",
    "purifying flames": "Seu Fogo Sagrado tem %s%% de chance de aumentar o seu dano Sagrado em %s%% por %s s.",
    "mental strength": "Aumenta o seu Intelecto total em %s%% e a sua velocidade de lançamento de feitiços em %s%%.",
    "enlighten": "Coloca um membro do grupo sob sua tutela por %s s. Lançar feitiços de Disciplina ou Sagrados tem chance de queimar o alvo em %s%% da vida como dano Sagrado e aumentar o dano mágico e cura de ambos em %s%% por %s s (aumenta para %s%% se lançado em si mesmo).",
    "resurgent shield": "Quando sua Palavra de Poder: Escudo é quebrada, %s%% do seu custo base de mana é restituído e aumenta o dano e a cura de feitiços Sagrados em até %s%% do valor total de absorção do escudo por %s s.",
    "force of will": "Aumenta o seu dano mágico e a chance de acerto crítico dos seus feitiços ofensivos em %s%% e o dano absorvido pela Palavra de Poder: Escudo em %s%%.",
    "chastise": "Castiga o alvo, causando %s de dano Sagrado. Se for inimigo, fica desorientado por até %s s. Se for aliado, sua velocidade de ataque e lançamento aumenta em %s%% por %s s (aumenta para %s s em acerto crítico).",
    "improved renew": "Aumenta a quantidade curada pelo seu feitiço Renovar em %s%%.",
    "holy focus": "Concede %s%% de chance de evitar interrupções causadas por dano enquanto lança qualquer feitiço Sagrado.",
    "divinity": "Aumenta a chance de efeito crítico dos seus feitiços Sagrados e de Disciplina em %s%%.",
    "divine fury": "Reduz o tempo de lançamento dos seus feitiços Punição, Fogo Sagrado, Cura e Cura Maior em %s s.",
    "spell warding": "Reduz todo o dano mágico sofrido em %s%%.",
    "holy reach": "Aumenta o alcance dos seus feitiços Punição, Fogo Sagrado e Castigar e o raio da sua Oração de Cura e Nova Sagrada em %s%%.",
    "blessed recovery": "Após sofrer um acerto crítico corpo a corpo ou à distância, cura %s%% do dano sofrido ao longo de %s s.",
    "inspiration": "Aumenta a armadura do alvo em %s%% por %s s após obter um efeito crítico com Cura Relâmpago, Cura, Cura Maior ou Oração de Cura.",
    "holy nova": "Provoca uma explosão de luz sagrada ao redor do sacerdote, causando %s de dano Sagrado a todos os inimigos a até %s m e curando membros do grupo a até %s m em %s. Causa ameaça reduzida.",
    "empowered recovery": "Aumenta a duração de Renovar em %s s e aumenta a cura realizada pelos seus feitiços de cura em %s%% contra alvos afetados por Renovar.",
    "improved healing": "Reduz o custo de mana dos seus feitiços Cura Menor, Cura, Cura Maior e Oração de Cura em %s%%.",
    "spiritual guidance": "Aumenta o dano mágico e a cura em até %s%% do seu total de Espírito.",
    "book of prayer": "Sempre que lançar um feitiço de cura, recupera %s%% do custo de mana se ele for diferente do feitiço de cura anterior.",
    "spirit of redemption": "Aumenta o Espírito total em %s%%. Ao morrer, torna-se o Espírito da Redenção por %s s, podendo lançar feitiços de cura sem custo.",
    "reservoir of light": "Aumenta a eficácia do Esplendor de Luz da Fonte de Luz em %s%%.",
    "spiritual healing": "Aumenta a quantidade curada pelos seus feitiços de cura em %s%%.",
    "ascendance": "Invoca auxílio divino, removendo todos os efeitos de controle de grupo e fortalecendo seus feitiços de cura. Feitiços de cura custam %s%% a menos de mana e seu tempo de lançamento é reduzido em %s%%. Aliados curados recebem Apoteose, aumentando a cura recebida em %s%% por %s s. Dura %s s.",
    "spirit tap": "Concede %s%% de chance de ganhar um bônus de %s%% no Espírito após matar um alvo ou com acerto crítico de Impacto Mental. O mana regenera a %s%% durante lançamentos por %s s.",
    "improved mind blast": "Reduz o tempo de recarga do seu feitiço Impacto Mental em %s s.",
    "shadow affinity": "Reduz a ameaça gerada pelos seus feitiços de Sombra em %s%%.",
    "improved shadow word: pain": "Aumenta a duração do seu feitiço Palavra de Sombra: Dor em %s s.",
    "shadow focus": "Reduz a chance do alvo resistir aos seus feitiços de Sombra em %s%%.",
    "blackout": "Concede aos seus feitiços de dano de Sombra %s%% de chance de atordoar o alvo por %s s.",
    "improved psychic scream": "Reduz o tempo de recarga do seu feitiço Grito Psíquico em %s s.",
    "improved fade": "Reduz o tempo de recarga de Desvanecer em %s s e a ameaça restaurada ao término em %s%%.",
    "mind flay": "Ataca a mente do alvo com energia de Sombra, causando %s de dano de Sombra ao longo de %s s e reduzindo a sua velocidade de movimento em %s%%.",
    "improved mana burn": "Reduz o tempo de lançamento do seu feitiço Queimadura de Mana em %s s.",
    "shadow reach": "Aumenta o alcance dos seus feitiços de dano de Sombra em %s%%.",
    "shadow weaving": "Seus feitiços de dano de Sombra têm %s%% de chance de conceder Tecedura das Sombras por %s s, aumentando o dano de Sombra sofrido pelo alvo em %s%% por acúmulo por %s s. Acumula até %s vezes.",
    "silence": "Silencia o alvo, impedindo-o de lançar feitiços por %s s.",
    "vampiric embrace": "Aflige o alvo com energia de Sombra por %s s, fazendo todos os membros do grupo serem curados em %s%% de qualquer dano de feitiço de Sombra causado.",
    "vampiric touch": "Aumenta a porcentagem curada por Abraço Vampírico em %s%% adicionais e faz o Abraço Vampírico conceder mana a todos os membros do grupo equivalente a %s%% do dano de feitiço de Sombra causado.",
    "darkness": "Aumenta o dano dos seus feitiços de Sombra em %s%%.",
    "shadowform": "Assume uma Forma de Sombra, aumentando o seu dano de Sombra em %s%% e reduzindo o dano físico sofrido em %s%%. Feitiços Sagrados não podem ser lançados nesta forma, com exceção de Nova Sagrada."
}

MAGE = {
    "arcane subtlety": "Reduz a resistência do alvo a todos os seus feitiços em %s e reduz a ameaça gerada pelos seus feitiços Arcanos em %s%%.",
    "magic absorption": "Aumenta todas as resistências em %s e, sempre que um feitiço seu for resistido, você restaura %s%% do seu mana máximo. Ocorre uma vez a cada 2 s.",
    "improved arcane missiles": "Concede a você %s%% de chance de evitar interrupções causadas por dano enquanto canaliza Mísseis Arcanos.",
    "wand specialization": "Aumenta o seu dano e chance de acerto com Varinhas em %s%% e %s%%, respectivamente. Ataques bem-sucedidos têm chance de restaurar %s de mana.",
    "arcane focus": "Reduz a chance de oponentes resistirem aos seus feitiços Arcanos em %s%%.",
    "arcane concentration": "Concede %s%% de chance de entrar em Lançamento Livre após atingir com feitiços de dano. Reduz o custo de mana do próximo feitiço em %s%%. Ocorre uma vez a cada 8 s.",
    "magic attunement": "Aumenta o efeito dos seus feitiços Amplificar Magia e Atenuar Magia em %s%% e permite que sejam lançados em inimigos até nível 62.",
    "arcane impact": "Aumenta a chance de acerto crítico dos seus feitiços Arcanos em %s%% adicionais.",
    "arcane rupture": "Rompe o alvo com força de energia arcana concentrada, causando %s de dano Arcano e aumentando o dano e custo de mana de Mísseis Arcanos em %s%% por %s s.",
    "improved mana shield": "Diminui o mana perdido por ponto de dano absorvido pelo Escudo de Mana em %s%%.",
    "improved counterspell": "Concede ao seu Contrafeitiço %s%% de chance de silenciar o alvo por %s s.",
    "temporal convergence": "Seus Mísseis Arcanos têm %s%% de chance de reiniciar a recarga de Ruptura Arcana e restituir o custo base no próximo lançamento. Ocorre uma vez a cada 15 s.",
    "arcane meditation": "Permite que %s%% da sua regeneração de mana continue durante o lançamento. Esse efeito é triplicado abaixo de %s%% de mana total.",
    "arcane instability": "Feitiços Arcanos de dano bem-sucedidos têm %s%% de chance de irromper, consumindo 2%% do mana base para causar %s%% a mais de dano.",
    "presence of mind": "Quando ativado, seu próximo feitiço de Mago com tempo de lançamento inferior a 10 s torna-se um feitiço instantâneo.",
    "accelerated arcana": "Aumenta a velocidade de lançamento dos seus feitiços Arcanos em %s%%. Acelera a recuperação de recargas arcanas e os pulsos de Mísseis Arcanos.",
    "arcane potency": "Aumenta o bônus de dano de acerto crítico dos seus feitiços Arcanos em %s%%.",
    "resonance cascade": "Feitiços Arcanos de dano bem-sucedidos têm %s%% de chance de se duplicarem causando %s%% do dano. Mísseis Arcanos duplicados são canalizados em conjunto.",
    "arcane power": "Quando ativado, sua velocidade de lançamento aumenta em %s%%, mas drena %s%% do seu mana máximo por segundo e reduz todo ganho de mana em %s%%. Se ficar abaixo de 10%% de mana, explode instantaneamente. Dura %s s.",
    "improved fireball": "Reduz o tempo de lançamento do seu feitiço Bola de Fogo em %s s.",
    "impact": "Concede aos seus feitiços de Fogo %s%% de chance de atordoar o alvo por %s s.",
    "ignite": "Acertos críticos de feitiços de dano de Fogo fazem o alvo queimar em 8%% adicionais do dano do feitiço ao longo de %s s.",
    "flame throwing": "Aumenta o alcance dos seus feitiços de Fogo em %s m e o raio da sua Onda de Chamas em %s%%.",
    "improved fire blast": "Reduz o tempo de recarga da sua Explosão de Fogo em %s s e sua recarga global em %s s.",
    "incinerate": "Aumenta a chance de acerto crítico dos seus feitiços Explosão de Fogo e Queimar em %s%%.",
    "improved flamestrike": "Aumenta a chance de acerto crítico do seu feitiço Golpe Flamejante em %s%%.",
    "pyroblast": "Lança uma imensa pedra de fogo que causa %s de dano de Fogo e %s adicionais de dano de Fogo ao longo de %s s.",
    "burning soul": "Concede aos seus feitiços de Fogo %s%% de chance de não perder tempo de lançamento ao sofrer dano e reduz a ameaça gerada em %s%%.",
    "fire vulnerability": "Seus feitiços Queimar e Explosão de Fogo têm %s%% de chance de causar vulnerabilidade a Fogo no alvo em %s%% por %s s. Acumula até %s vezes.",
    "improved fire ward": "Concede à sua Proteção contra o Fogo %s%% de chance de refletir feitiços de Fogo enquanto ativa.",
    "master of elements": "Acertos críticos com feitiços de Fogo e Gelo restituem %s%% do seu custo base de mana.",
    "blast wave": "Uma onda de chamas irradia ao redor do lançador, atingindo inimigos a até %s m causando %s de dano de Fogo e deixando-os pasmos por %s s.",
    "critical mass": "Aumenta a chance de acerto crítico dos seus feitiços de Fogo em %s%%.",
    "hot streak": "Acertos críticos de Bola de Fogo e Explosão de Fogo têm %s%% de chance de conceder Boa Sequência, reduzindo o tempo de lançamento de Ignimpacto em %s s por acúmulo por %s s. Acumula até %s vezes.",
    "fire power": "Aumenta o dano causado pelos seus feitiços de Fogo em %s%%.",
    "combustion": "Quando ativado, cada feitiço de dano de Fogo lançado aumenta a sua chance de acerto crítico em %s%% cumulativos até obter %s acertos críticos.",
    "frost warding": "Aumenta a armadura e resistências da sua Armadura de Gelo e Armadura de Geada em %s%%. Concede à Proteção contra o Gelo %s%% de chance de refletir feitiços.",
    "improved frostbolt": "Reduz o tempo de lançamento da sua Seta de Gelo em %s s.",
    "elemental precision": "Reduz a chance de oponentes resistirem aos seus feitiços de Gelo e Fogo em %s%%.",
    "piercing ice": "Aumenta o dano causado pelos seus feitiços de Gelo em %s%%.",
    "frostbite": "Concede aos seus efeitos de Resfriamento %s%% de chance de congelar o alvo por %s s.",
    "improved frost nova": "Reduz o tempo de recarga da sua Nova de Gelo em %s s.",
    "permafrost": "Aumenta a duração dos seus efeitos de Resfriamento em %s s e reduz a velocidade do alvo em %s%% adicionais.",
    "ice shards": "Aumenta o bônus de dano de acerto crítico dos seus feitiços de Gelo em %s%%.",
    "cold snap": "Quando ativado, este feitiço encerra a recarga de todos os seus feitiços de Gelo.",
    "improved blizzard": "Adiciona um efeito de congelamento à sua Nevasca, reduzindo a velocidade de movimento do alvo em %s%% por %s s.",
    "arctic reach": "Aumenta o alcance de Seta de Gelo, Sincelos e Nevasca e o raio de Nova de Gelo e Cone de Frio em %s%%.",
    "frost channeling": "Reduz o custo de mana dos seus feitiços de Gelo em %s%% e a ameaça gerada em %s%%.",
    "shatter": "Aumenta a chance de acerto crítico de todos os seus feitiços contra alvos congelados em %s%%.",
    "ice block": "Você fica envolto em um bloco de gelo, protegendo-se contra todos os ataques físicos e feitiços por %s s, mas não pode atacar, mover-se ou lançar feitiços.",
    "icicles": "Canaliza linhas de gelo ficando congelado no lugar e dispara sincelos contra o inimigo, causando %s de dano de Gelo a cada %s s por %s s. Sofrer dano pode quebrar a prisão causando 30%% da sua vida máxima como dano a você.",
    "improved cone of cold": "Aumenta o dano causado pelo seu feitiço Cone de Frio em %s%%.",
    "winter's chill": "Seus feitiços de dano de Gelo têm %s%% de chance de aplicar Calafrio de Inverno, aumentando a chance de acerto crítico de feitiços de Gelo em %s%% por %s s. Acumula até %s vezes.",
    "flash freeze": "Se um efeito de congelamento não for aplicado devido a imunidade do alvo, você tem %s%% de chance de receber Congelamento Rápido, reiniciando a recarga de Sincelos e reduzindo a duração e intervalo em %s%%.",
    "ice barrier": "Cria instantaneamente um escudo protetor, absorvendo %s de dano e aumentando o dano de Gelo em %s%% por %s s. Enquanto durar, feitiços não são interrompidos e o dano de Gelo aumenta em %s%% adicionais."
}
